### ISSUE TITLE
problem with npm install

### ISSUE THREAD

**Issue by GreyCoder25** [minosworld/minos#115]
Hello. I tried minos earlier and it worked fine but a few days ago I decided to run it and something went wrong. So, I decided to reinstall it and got some errors after invoking "NODE_TLS_REJECT_UNAUTHORIZED=0 npm install" (for me it doesn't work without setting this flag to 0) and "npm config set strict-ssl false" before it(to solve problem with self-signed certificate in a chain which I also have).
Error messages are next:

(node:25068) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
ERROR: Download of https://dl.bintray.com/lovell/sharp/libvips-8.5.5-linux-x64.tar.gz failed: read ECONNRESET
gyp: Call to 'node -e "require('./binding').download_vips()"' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/home/serhii/.nvm/versions/node/v11.1.0/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
gyp ERR! System Linux 4.4.0-21-generic
gyp ERR! command "/home/serhii/.nvm/versions/node/v11.1.0/bin/node" "/home/serhii/.nvm/versions/node/v11.1.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/serhii/PycharmProjects/minos/minos/server/node_modules/sstk/node_modules/sharp
gyp ERR! node -v v11.1.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN sstk No repository field.
npm WARN sstk No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sharp@0.18.4 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sharp@0.18.4 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/serhii/.npm/_logs/2018-11-12T20_18_50_062Z-debug.log
-------------------------------------------------------------------------------------------------------------------
In the end:

node-gyp rebuild

    at Promise.all.then.arr (/home/serhii/PycharmProjects/minos/minos/server/node_modules/execa/index.js:236:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
  code: 1,
  killed: false,
-----------------------------------------------------------------------------------------------------------------
And finally:

failed: true,
  signal: null,
  cmd: 'npm install',
  timedOut: false,
  exitCode: 1 }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sstk@0.5.3 bootstrap: `lerna bootstrap --hoist`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sstk@0.5.3 bootstrap script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/serhii/.npm/_logs/2018-11-12T20_18_50_493Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sstk@0.5.3 postinstall: `npm run bootstrap`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sstk@0.5.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/serhii/.npm/_logs/2018-11-12T20_18_52_526Z-debug.log

Help, please, to fix this problem.

**Comment by msavva** [comment]
Hi @GreyCoder25

The problem indeed appears to be with the recent node v11 release which breaks some of our npm dependencies.  Thank you for reporting this issue.  We have updated the instructions to explicitly install the latest node v10 version (i.e. run `nvm install v10.13.0`).  Please let us know if the issue has been resolved for you with the latest node v10.
