### ISSUE TITLE
Can we view the floor plan, top view, house map of Matter-port houses.?

### ISSUE THREAD

**Issue by DRAhmadFaraz** [minosworld/minos#118]
Can we view the floor plan, top view, house map of Matter-port houses.?

Regards

**Comment by angelxuanchang** [comment]
Please use http://dovahkiin.stanford.edu/matterport3d/scans/matterport3d/houses to explore the matterport houses.  You will also find the top-down images of the navgrids that are computed and used by Minos in the downloaded matterport data (under the navgrid_10 directory)

**Comment by angelxuanchang** [comment]
You can also view the levels and precomputed navgrid for minos at http://dovahkiin.stanford.edu/matterport3d/scans/matterport3d/levels
