### ISSUE TITLE
visualize_traces.js does not work for mp3d

### ISSUE THREAD

**Issue by ducha-aiki** [minosworld/minos#129]
Run with command: 

`./visualize_traces.js --trace_file action_trace.csv --show_shortest_path=True --allow_diag True --show_path true --dataset mp3d `

It crashes with 

> No navmap for scene mp3d.2t7WUuJeko7

If run without show_shortest_path and show_path, i.e. just visualizing the map, works fine. On suncg maps works fine

**Comment by angelxuanchang** [comment]
Thanks for reporting this.  This should be now fixed in the v0.6.x and v0.7.x branches.
