### ISSUE TITLE
Explicitly changing field of view

### ISSUE THREAD

**Issue by hzyjerry** [minosworld/minos#13]
Hi,

I'm wondering if there's an explicit way to change the default fov through MINOS code? Currently it seems that it's fixed to around 45~50 degrees.

Thanks

**Comment by msavva** [comment]
There is a related discussion in #4 . The `fov` parameter in `config/sensors.yml` controls the vertical field of view.  We are currently working on improving the documentation and structure of the codebase to clarify such configuration parameters.  Thanks for bearing with us in the meantime. :)

**Comment by hzyjerry** [comment]
Thanks! Will play around with that. Is there a way to also modify the horizontal field of view?

**Comment by msavva** [comment]
The horizontal field of view is currently determined from the aspect ratio of the image and the vertical field of view.

**Comment by hzyjerry** [comment]
Nice. It seems that instruction `python3 -m tools.pygame_client --source mp3d --scene_ids 17DRP5sb8fy` no longer works after python repackaging. What would be the correct way to kick start minos?

**Comment by msavva** [comment]
If you use the the `python-repackage` branch, the command will be of the form `python3 -m minos.tools.pygame_client`.  The main README.md on that branch is updated with these commands

**Comment by hzyjerry** [comment]
Thanks!
