### ISSUE TITLE
What does rotation means in action_trace file ? 

### ISSUE THREAD

**Issue by Usama323** [minosworld/minos#133]
When I save action_trace file, there is column of rotation, what does it means? the rotation is in degrees or radians ? Looking forward for the reply !

**Comment by DRAhmadFaraz** [comment]
I am also facing the same issues. "reply if you have solved this issue".

**Comment by angelxuanchang** [comment]
The rotation is the orientation of the agent encoded as a single angle in radius around the up axis (Y).

**Comment by Usama323** [comment]
radius is unit of angle ? or it is something else ?

**Comment by angelxuanchang** [comment]
sorry, radians

**Comment by Usama323** [comment]
Thanks @angelxuanchang for fast reply !

**Comment by Usama323** [comment]
One last question @angelxuanchang, that is this angle is in range of “-pi to pi” or “-2pi to 2pi” ?

**Comment by Usama323** [comment]
Thanks a lot for the response

**Comment by Usama323** [comment]
Hi @angelxuanchang  I have seen value of rotation in action_trace  files and it variate for different houses. How can one generalize it ? 
What is its range as in some files value of rotation is -10.8471 and in some files it is 0.4913. 
Also how to convert it in degree , if I use the well known formula to convert from radian to degree (1rad * 180/pi) then it gives value more than 360. 

Kindly reply me as soon as possible, looking forward for your reply. Thanks in advance for this act of kindness.
