### ISSUE TITLE
Definition of roomId, roomType, objectId, and objectType in SUNCG

### ISSUE THREAD

**Issue by playerkk** [minosworld/minos#14]
What can I find their definitions? I didn't find much information on SUNCG's website. Thanks.

**Comment by playerkk** [comment]
If I understand correctly, I can get instance segmentation by combining objectId and objectType. Is it correct?

I see there is objectGoal task, is there detailed description of this task? For example, how is the object specified, an image?

Thanks.

**Comment by playerkk** [comment]
If I understand correctly, I can get instance segmentation by combining objectId and objectType. Is it correct?

Thanks.

**Comment by angelxuanchang** [comment]
The objectId gives the instance segmentation without the semantic type.  If you include the objectType, then you will get the instance semantic segmentation.

**Comment by playerkk** [comment]
Thanks a lot. Will close the issue.
