### ISSUE TITLE
fatal: Not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by DRAhmadFaraz** [minosworld/minos#140]
Get this error after all steps successfully and run empty room command or mp3d by typing 

"python3 -m minos.tools.pygame_client --dataset mp3d --scene_ids 2t7WUuJeko7 --env_config pointgoal_mp3d_s"

![screenshot from 2018-12-20 21-19-03](https://user-images.githubusercontent.com/38114191/50311444-26de7300-049d-11e9-858c-4b227f85e69e.png)

**Comment by angelxuanchang** [comment]
This has been fixed in v0.7.x branch of the code (we will ignore exceptions that comes from trying to track the git version).
