### ISSUE TITLE
How I can download Suncg data set, it's unavailable on the website! 

### ISSUE THREAD

**Issue by Jemmagu** [minosworld/minos#159]
How I can download Suncg data set, it seems unavailable on the Princeton website  and the agreement google docs has been cancelled. Please Kindly tell me how can I get access to the dataset. quite urgent!!

**Comment by Usama323** [comment]
Here is the issue kindly see this!

https://github.com/minosworld/minos/issues/94

**Comment by hzxie** [comment]
@Usama323 
However, the links are unavailable now. 
I sent several emails to the team, but they didn't reply.

**Comment by Usama323** [comment]
@hzxie  I have rechecked it, it is gone now. I also need that data, any author kindly respond to this problem as soon as possible! @msavva  @angelxuanchang

**Comment by pemo-ml** [comment]
I do not think that the data set will be made available again anytime soon: https://www.law.com/therecorder/2019/06/06/home-design-site-claims-facebook-princeton-nabbed-data-for-3-d-objects/

**Comment by gyzhang123** [comment]
can we get some samples like that ?
