### ISSUE TITLE
Change to complex environment in Gym

### ISSUE THREAD

**Issue by dangkh** [minosworld/minos#25]
Hi, 
How can I change a simple environment in Gym to another complex? that environment comprises some stuffs such as chair, washing machine, table ,... Thanks

**Comment by msavva** [comment]
@dangkh , can you clarify what you mean by "another complex environment"? Do you mean how you would specify a different set of scenes for a given experiment?

**Comment by dangkh** [comment]
@msavva sorry for my confuse question. I mean, the environment in gym is empty house and there are no objects in that one. I want to add more objects into the environment like that 
![envi](https://user-images.githubusercontent.com/14333453/37318304-4d68b4ca-269c-11e8-82eb-5a7122b07e79.jpg)

**Comment by msavva** [comment]
You can specify the environment configuration through the `--env_config` command line argument. For example: `python3 demo.py --env_config objectgoal_suncg_mf` will use the `objectgoal_suncg_mf` environment configuration.  See the configuration files in https://github.com/minosworld/minos/tree/master/minos/config/envs for the details of each preset.  Files with the `_sf` or `_mf` indicate furnished SUNCG houses.

**Comment by dangkh** [comment]
@msavva Thanks for your reply. By the way, I'm trying to get depth image from observation in gym. The sensors.yml had already configuration for depth camera. Returned data in Simulator.py is only color image. Can you give me some suggestions. Thanks again.

**Comment by msavva** [comment]
@dangkh To enable depth output you need to specify the `--depth` command line argument, or set `"depth":True` in the `observations` variable in `sim_config.py`.
