### ISSUE TITLE
Is there  plane segmentation  result ?

### ISSUE THREAD

**Issue by huangkuns** [minosworld/minos#32]
I tried the demo, the plane seems well segmented, like walls, windows, cainets etc. I'm wondering is there any plane segmentation result from SUNCG or mattport3d data.

**Comment by msavva** [comment]
@huangkuns can you clarify what you mean by plane segmentation? Do you mean the semantic segmentation mask indicating category labels for the objects?

**Comment by huangkuns** [comment]
@msavva  Thanks for replying. By plane/surface segmentation, I mean areas that  belong to the same plane/surface. For example, windows/doors are on the same plane as one side of wall. Ceiling and wall are on two orthogonal plane.

**Comment by msavva** [comment]
We do not currently have a plane segmentation mode.  However, you can probably use the surface normal sensor to extract planar segments.  You can enable this sensor by using the `--sensor normal` command line argument, or by manually setting `normal: True` in the `observations` parameter.

**Comment by msavva** [comment]
@huangkuns did this information answer your question? If so, let's mark the issue as resolved.

**Comment by msavva** [comment]
Please re-open issue if additional information is required.
