### ISSUE TITLE
How to get Agent trajectory image?

### ISSUE THREAD

**Issue by hasifast** [minosworld/minos#68]
How can i get the image as shown in figure1(b)of paper (MINOS: Multimodal Indoor Simulator
for Navigation in Complex Environments) of agent trajectory where i have navigated.
I actually want to see the path the agent has followed.
Image is shown here,
![image](https://user-images.githubusercontent.com/30036365/41901915-99f0ba2a-794b-11e8-9939-2454b3ce5d77.png)

**Comment by msavva** [comment]
Please see https://github.com/minosworld/minos/blob/dev/FAQ.md#getting-shortest-path-to-goal-and-navigation-map-data for the relevant parameters.  The gym `demo.py` also includes example code that saves the navigation map and visualized shortest path from agent position to goal at each step.  You can try this by running `python3 demo.py -s map --save_observations`.

If by "path" you mean the traversed path, then that is not actually what the above visualization plots.  You can create a path visualization using the `minos/server/visualize_traces.js` script as follows:
- Run using the `--log_action_trace` argument (e.g., `python3 demo.py --log_action_trace`)
- Inspect the output in `logs/<timestamp>/action_trace.csv`.  This file is a recording of all agent steps
- Run the visualization script (e.g., `./visualize_traces.js --trace_file ../../gym/logs/<timestamp>/action_trace.csv`)
- Inspect the visualization png files written to the working directory -- there will be one file per episode visualizing the agent path and the goal object (in green)

The `visualize_traces.js` script has additional parameters to control the output that you can see by running with the `-h` argument.
