### ISSUE TITLE
Gym environment width and height bug

### ISSUE THREAD

**Issue by devendrachaplot** [minosworld/minos#9]
I ran `python demo.py --env_config roomgoal_mp3d_s --width 400 --height 225` in the gym folder and it's showing me a frame of height 400 and width 225. Also the pixels in the frame are garbled up. Am I missing something?

**Comment by msavva** [comment]
Thank you for reporting this bug and apologies for the long delay in responding.  We just pushed a commit to master which should fix this issue.  Please let us know if you still experience any problem with setting arbitrary resolutions for the gym client.

**Comment by msavva** [comment]
@devendrachaplot 

Was the issue resolved on your end?

**Comment by devendrachaplot** [comment]
Yeah, I just tried it, it's fixed. Thanks a lot.
