### ISSUE TITLE
Train/val/test split file is invalid

### ISSUE THREAD

**Issue by ZhuFengdaaa** [minosworld/minos#92]
This two link in both FAQ and [issue 18](https://github.com/minosworld/minos/issues/18) is invalid. 
* [data/episodes_states.suncg.csv.bz2](https://github.com/minosworld/minos/blob/master/data/episode_states.mp3d.csv.bz2)
* [data/episodes_states.mp3d.csv.bz2](https://github.com/minosworld/minos/blob/master/data/episode_states.mp3d.csv.bz2)

**Comment by msavva** [comment]
Thanks for pointing this out, the links in #18 are invalid due to code reorganization that has happened since that issue.  We updated the links in the FAQ (https://github.com/minosworld/minos/blob/master/FAQ.md#where-are-the-trainvaltest-splits-defined-and-how-are-episodes-sampled) to be correct.
