### ISSUE TITLE
 Where is texture file located for matterport data ?

### ISSUE THREAD

**Issue by Usama323** [minosworld/minos#93]
I need its folder path kindly

**Comment by angelxuanchang** [comment]
When using the glb format (default) for the matterport3d, the textures are embedded in the glb files.  You can choose to use the obj/mtl format and then the textures are in the same directory as each obj file - you will need to obtain the matterport data by requesting access at https://niessner.github.io/Matterport/

**Comment by Usama323** [comment]
which software i can use to open this glb file and can you kindly share its folder in minos data ?

**Comment by angelxuanchang** [comment]
The MINOS simulator will automatically load the glb file for a matterport3d scene.  There are many gltf/glb viewers (for instance, https://gltf-viewer.donmccurdy.com/ is an online viewer for gltf)
